server:
  port: 8085
  undertow:
    uri-encoding: urf-8
    io-threads: 8
    worker-threads: 64
    buffer-size: 1024
    direct-buffers: true
debug: true

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.25.253.85:3306/adott?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    pool:
      max-active: 4
      max-wait: -1
      max-idle: 4
      min-idle: 0
    first:
      database: 0
      host: 172.25.253.85
      port: 6379
      password:
      timeout: 2000
    second:
      database: 0
      host: 172.25.253.85
      port: 6379
      password:
      timeout: 2000
    third:
      database: 0
      host: 172.25.253.85
      port: 6379
      password:
      timeout: 2000
mybatis:
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml

